### ISSUE TITLE
regular expression for validating domain name rejects legal ones

### ISSUE THREAD

**Issue by http600** [livekit/deploy#1]
https://github.com/livekit/deploy/blob/eb5eeaa45063c8ba55573f2d9aa3af388384c048/generate/production.go#L22

I think `a.example.com` will be rejected, although it is a valid one indeed

**Comment by davidzhao** [comment]
yeah.. that makes sense. it should be tweaked

**Comment by bekriebel** [comment]
Just had a user report that this also rejects `.co.uk` domains.
