### ISSUE TITLE
generate does not support Podman

### ISSUE THREAD

**Issue by sammydre** [livekit/deploy#4]
Due to detecting running under Docker via looking for the file `/.dockerenv`.

Podman doesn't create this file, instead creating `/run/.containerenv`. See e.g. https://github.com/containers/podman/issues/648

The fix should be simple enough, also checking for the presence of `/run/.containerenv` in the `isDocker()` function.

**Comment by sammydre** [comment]
I should add I worked around it via the following:

```
touch empty
docker run --rm -v $(pwd):/output -v empty:/.dockerenv  livekit/generate --local
```

**Comment by davidzhao** [comment]
thanks for the report! that's a good insight. We'll modify this in the generator.

**Comment by davidzhao** [comment]
@sammydre I think this should have fixed it. Do you want to `docker pull` the image and see if it's working for you without the workaround?

**Comment by sammydre** [comment]
Yes, I can confirm that fixes it @davidzhao . Thanks!

**Comment by davidzhao** [comment]
awesome! thanks for the report and your insights!
